server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/xe
    username: ${datasource.username}
    password: ${datasource.password} 