name: deploy

on:
  push:
    branches:
      - main-deploy

permissions:
  contents: read
      
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: checkout
      uses: actions/checkout@master

    - name: create secure file
      run: |
        cd src/main/resources
        touch secure.properties
        echo "${{ secrets.SECURE }}" >> secure.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build --stacktrace

    - name: Transfer WAR file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        source: "meevote-0.0.1-SNAPSHOT.war"
        target: "/home/ubuntu/"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd /home/ubuntu/
          sudo nohup java -jar -Dspring.profiles.active=prod -Duser.timezone="Asia/Seoul" meevote-0.0.1-SNAPSHOT.war &
